"use client";

import * as React from "react";
import { Dialog } from "@/components/ui/overlay";
import { Button } from "@/components/ui/primitives";
import { Check, Copy, GitFork } from "lucide-react";

/**
 * Shows the shareable link generated by pruning a subtree. The link
 * (/p/:planId?subtree=<ids>) opens the canvas scoped to exactly those nodes, so a
 * teammate/agent can run that subtree without the rest of the plan.
 */
export function PruneShareDialog({
  open,
  onClose,
  link,
  count,
}: {
  open: boolean;
  onClose: () => void;
  link: string;
  count: number;
}) {
  const [copied, setCopied] = React.useState(false);

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title="Delegate subtree"
      footer={
        <Button variant="ghost" onClick={onClose}>
          Done
        </Button>
      }
    >
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-sm font-medium text-fg">
          <GitFork size={15} className="text-accent" aria-hidden />
          Pruned subtree · {count} task{count === 1 ? "" : "s"}
        </div>
        <p className="text-xs text-fg-muted">
          Send this link to a teammate or agent. They&apos;ll open the canvas scoped to exactly these nodes and can run
          that subtree on its own.
        </p>
        <div className="flex gap-1.5">
          <input
            readOnly
            value={link}
            onFocus={(e) => e.currentTarget.select()}
            className="w-full rounded-md border border-border bg-surface px-2.5 py-1.5 font-mono text-xs text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"
          />
          <Button
            variant="secondary"
            icon={copied ? <Check size={13} /> : <Copy size={13} />}
            onClick={() => {
              navigator.clipboard?.writeText(link);
              setCopied(true);
              setTimeout(() => setCopied(false), 1500);
            }}
          >
            {copied ? "Copied" : "Copy"}
          </Button>
        </div>
        <p className="text-[11px] text-fg-muted">
          Recipients need access to this Trellis instance. (Production: this becomes a durable delegation record / A2A
          hand-off — see subtree-delegation.md.)
        </p>
      </div>
    </Dialog>
  );
}
