import { mkdir, rm, stat, writeFile, readdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { simpleGit, type SimpleGit } from "simple-git";
import { env } from "./env.js";
import { logger } from "./log.js";

const log = logger("worktree");

/**
 * Git repo cache + ephemeral worktree helpers (builder-agent.md §3, ADR-3).
 *
 * Trellis owns physical isolation: one worktree per branch off base_commit. We
 * use simple-git over a cached bare-ish clone under REPO_CACHE_ROOT, and create
 * detached worktrees under WORKTREE_ROOT. Everything degrades: a missing/unclonable
 * repo falls back to a tiny sample repo so the rest of the pipeline still runs.
 */

function repoCacheDir(projectId: string): string {
  // One cache dir per project; stable across plans on the same repo.
  const safe = createHash("sha1").update(projectId).digest("hex").slice(0, 16);
  return join(env.repoCacheRoot, safe);
}

/** Inject GITHUB_TOKEN into an https github URL for cloning private repos. */
function authedUrl(repoUrl: string): string {
  if (!env.githubToken) return repoUrl;
  try {
    const u = new URL(repoUrl);
    if (u.protocol === "https:" && /github\.com$/.test(u.hostname)) {
      u.username = "x-access-token";
      u.password = env.githubToken;
      return u.toString();
    }
  } catch {
    /* not a URL — leave as-is */
  }
  return repoUrl;
}

export interface RepoHandle {
  /** Path to the working clone (real or sample). */
  path: string;
  /** The resolved base commit SHA we planned/built against. */
  baseCommit: string;
  /** True when we degraded to a generated sample instead of the real repo. */
  isSample: boolean;
  git: SimpleGit;
}

/**
 * Ensure a usable repo checkout for a project exists locally.
 * - If already cached, fetch + return.
 * - Else clone with GITHUB_TOKEN.
 * - On any failure (no URL, clone error, no network), generate a tiny sample
 *   git repo so indexing/planning/building still have *something* to operate on.
 */
export async function ensureRepo(
  projectId: string,
  repoUrl: string | null | undefined,
  defaultBranch = "main",
  desiredCommit?: string | null,
): Promise<RepoHandle> {
  const dir = repoCacheDir(projectId);
  await mkdir(env.repoCacheRoot, { recursive: true }).catch(() => {});

  const alreadyCloned = existsSync(join(dir, ".git"));

  if (!alreadyCloned && repoUrl) {
    try {
      log.info(`cloning ${repoUrl} -> ${dir}`);
      await mkdir(dir, { recursive: true });
      const g = simpleGit();
      await g.clone(authedUrl(repoUrl), dir, ["--depth", "50"]);
    } catch (err) {
      log.warn(`clone failed (${(err as Error).message}); degrading to sample`);
      return sampleRepo(dir);
    }
  } else if (!alreadyCloned && !repoUrl) {
    log.warn("no repo_url on project; degrading to sample repo");
    return sampleRepo(dir);
  }

  const git = simpleGit(dir);
  try {
    // Best-effort refresh; offline is fine.
    await git.fetch(["--all", "--prune"]).catch(() => {});
    if (desiredCommit) {
      await git.checkout(desiredCommit).catch(() => {});
    } else {
      await git.checkout(defaultBranch).catch(() => {});
    }
    const baseCommit = (await git.revparse(["HEAD"]).catch(() => "")) || "";
    return { path: dir, baseCommit, isSample: false, git };
  } catch (err) {
    log.warn(`repo open failed (${(err as Error).message}); degrading to sample`);
    return sampleRepo(dir);
  }
}

/** Generate a minimal, committed git repo so the pipeline has real files. */
async function sampleRepo(dir: string): Promise<RepoHandle> {
  const sampleDir = `${dir}-sample`;
  await rm(sampleDir, { recursive: true, force: true }).catch(() => {});
  await mkdir(join(sampleDir, "src"), { recursive: true });
  await writeFile(
    join(sampleDir, "src", "index.ts"),
    `export function main(): string {\n  return "hello trellis";\n}\n`,
  );
  await writeFile(
    join(sampleDir, "README.md"),
    `# Sample repo\n\nGenerated by Trellis workers because the real repo was unavailable.\n`,
  );
  await writeFile(
    join(sampleDir, "package.json"),
    JSON.stringify({ name: "trellis-sample", version: "0.0.0", scripts: { test: "echo ok" } }, null, 2),
  );
  const git = simpleGit(sampleDir);
  try {
    await git.init();
    await git.addConfig("user.email", "workers@trellis.local");
    await git.addConfig("user.name", "Trellis Workers");
    await git.add(".");
    await git.commit("chore: sample scaffold");
  } catch (err) {
    log.warn(`sample repo init issue: ${(err as Error).message}`);
  }
  const baseCommit = (await git.revparse(["HEAD"]).catch(() => "")) || "";
  return { path: sampleDir, baseCommit, isSample: true, git };
}

export interface Worktree {
  path: string;
  ref: string;
  git: SimpleGit;
  /** Remove the worktree (best-effort GC). */
  remove(): Promise<void>;
}

/**
 * Create an ephemeral, detached worktree off `baseCommit` under WORKTREE_ROOT.
 * The branch ref is recorded; callers diff this worktree at the end.
 */
export async function createWorktree(repo: RepoHandle, label: string, baseCommit: string): Promise<Worktree> {
  await mkdir(env.worktreeRoot, { recursive: true }).catch(() => {});
  const id = `${label}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
  const wtPath = join(env.worktreeRoot, id);
  const ref = `trellis/${id}`;
  const base = baseCommit || repo.baseCommit;

  try {
    // Detached worktree at the base commit, then a working branch ref.
    await repo.git.raw(["worktree", "add", "--detach", wtPath, base]);
    const wtGit = simpleGit(wtPath);
    await wtGit.checkout(["-b", ref]).catch(() => {});
    return makeWorktree(repo, wtPath, ref);
  } catch (err) {
    log.warn(`git worktree add failed (${(err as Error).message}); using copy fallback`);
    // Fallback: a plain directory copy of the working tree (no git history),
    // still isolated, still diffable via our own snapshot.
    await mkdir(wtPath, { recursive: true });
    await copyDir(repo.path, wtPath);
    const wtGit = simpleGit(wtPath);
    await wtGit.init().catch(() => {});
    await wtGit.addConfig("user.email", "workers@trellis.local").catch(() => {});
    await wtGit.addConfig("user.name", "Trellis Workers").catch(() => {});
    await wtGit.add(".").catch(() => {});
    await wtGit.commit("chore: worktree base").catch(() => {});
    return makeWorktree(repo, wtPath, ref);
  }
}

function makeWorktree(repo: RepoHandle, wtPath: string, ref: string): Worktree {
  const wtGit = simpleGit(wtPath);
  return {
    path: wtPath,
    ref,
    git: wtGit,
    async remove() {
      try {
        await repo.git.raw(["worktree", "remove", "--force", wtPath]).catch(() => {});
      } catch {
        /* ignore */
      }
      await rm(wtPath, { recursive: true, force: true }).catch(() => {});
    },
  };
}

async function copyDir(src: string, dest: string): Promise<void> {
  const entries = await readdir(src, { withFileTypes: true });
  for (const e of entries) {
    if (e.name === ".git") continue;
    const s = join(src, e.name);
    const d = join(dest, e.name);
    if (e.isDirectory()) {
      await mkdir(d, { recursive: true });
      await copyDir(s, d);
    } else if (e.isFile()) {
      await writeFile(d, await readFile(s));
    }
  }
}

/** `git diff` of a worktree against its first commit / base. Returns the patch text. */
export async function diffWorktree(wt: Worktree): Promise<string> {
  try {
    // Stage everything so new files show in the diff, then diff against HEAD.
    await wt.git.add(["-A"]).catch(() => {});
    const cached = await wt.git.diff(["--cached"]).catch(() => "");
    if (cached.trim()) return cached;
    return await wt.git.diff().catch(() => "");
  } catch (err) {
    log.warn(`diff failed: ${(err as Error).message}`);
    return "";
  }
}

/** List files changed in a worktree (for the drift audit). */
export async function changedFiles(wt: Worktree): Promise<string[]> {
  try {
    await wt.git.add(["-A"]).catch(() => {});
    const out = await wt.git.raw(["diff", "--cached", "--name-only"]).catch(() => "");
    return out.split("\n").map((s) => s.trim()).filter(Boolean);
  } catch {
    return [];
  }
}

/** True if a path under the repo looks like it has a runnable test command. */
export async function detectTestCommand(repoPath: string): Promise<string | null> {
  try {
    const pkgPath = join(repoPath, "package.json");
    const st = await stat(pkgPath).catch(() => null);
    if (!st) return null;
    const pkg = JSON.parse(await readFile(pkgPath, "utf8")) as { scripts?: Record<string, string> };
    if (pkg.scripts?.test && !/no test specified/i.test(pkg.scripts.test)) {
      return "npm test";
    }
  } catch {
    /* ignore */
  }
  return null;
}
